import type { Metadata } from 'next';

import Header from './(public)/(components)/Header';
import LandingFooter from './(public)/(components)/LandingFooter';
import LandingHeader from './(public)/(components)/LandingHeader';

import Footer from './(public)/(components)/Footer';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='flex flex-col min-h-screen'>
				<LandingHeader />

				<main className='flex-grow'>{children}</main>

				<LandingFooter />
			</body>
		</html>
	);
}
