import type { Metadata } from 'next';

import LandingHeader from './(public)/(components)/LandingHeader';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='flex flex-col mt-16'>
				<LandingHeader />
				{children}
			</body>
		</html>
	);
}
